(rocq.extraction
 (prelude SailExtraction)
 (extracted_modules
  Ascii
  Ast
  AstInduction
  BinInt
  BinNat
  BinNums
  BinPos
  Bit
  BitList
  Bool
  Datatypes
  FMapList
  IdUtil
  List0
  ListDef
  ListUtil
  Nat0
  OptionUtil
  OrderedType
  Orders
  OrdersAlt
  OrdersTac
  PatternMatch
  PeanoNat
  PosDef
  QArith_base
  Semantics
  Specif
  String0
  TypeAnnot
  ValueSemilattice
  ValueType
  Wf
  ZAst)
 (theories Stdlib Sail Ltac2))
