(*Generated by Lem from missing_pervasives.lem.*)
open Lem_num

open Lem_list

open Lem_basic_classes

open Lem_bool

open Lem_maybe

open Lem_string

open Lem_assert_extra

open Show

open Lem_sorting

open Missing_pervasives

let run_test n loc b =
  if b then (Format.printf "%s: ok\n" n) else ((Format.printf "%s: FAILED\n  %s\n\n" n loc); exit 1);;


(****************************************************)
(*                                                  *)
(* Assertions                                       *)
(*                                                  *)
(****************************************************)

let _ = run_test "split_string_null" "File \"missing_pervasives.lem\", line 418, character 1 to line 422, character 32\n" (
  (let afterSplit = (Ml_bindings.split_string_on_char (Xstring.implode ([null_char; 's'; null_char; 't']: char list)) null_char)
    in 
    let _ = (prerr_endline ("split string is " ^ (string_of_list 
  instance_Show_Show_string_dict afterSplit)))
    in (listEqualBy (=)
    afterSplit [""; "s"; "t"]))
)



