:conf: sail_doc/config.json

Sail includes a configuration system that allows building
specifications that can be configured at either runtime (if supported
by the Sail backend in use) or statically at build-time using a set of
options.

From the perspective of the specification author, one uses the
`config` construct to include a value in the specification, for
example:

sail::example1[from=conf,part=body,dedent]

The configuration is some key-value store with dot-separated
hierachical keys, so we access the value stored at `foo.bar` key as
some string value. In practice, we use JSON to represent these
configurations. In this example, the JSON might look something like:

[source,json]
----
include::sail_config/config.json[]
----

Which when used will cause the specification to print `"Hello,
World!"`. If we want to statically apply this configuration (and
convert the Sail source to OCaml), we could run the following,
assuming the configration file is called `file.json` and the Sail file
containing the above code is `file.sail`.

[source,sh]
----
sail --ocaml --config file.json file.sail
----

=== JSON representation of Sail types

The following example demonstrates how basic Sail types are
represented in the JSON configuration file. We can load integers,
booleans, and strings, all of which correspond directly to the
equivalent JSON type. Integers are allowed to be arbitrary precision,
as they are in Sail.

:confbasic: sail_doc/config_basic_types.json

sail::example[from=confbasic,part=body,dedent]

The following JSON can be used to instantiate the above Sail source:

[source,json]
----
include::sail_config/config_basic_types.json[]
----

Note the two permissible representations for bitvectors. First, we can
represent them as a list of JSON booleans. This representation has the
advantage of being simple and unambiguous regarding the length of the
bitvector, but is verbose. Second, we can use a string containing the
bitvector value formatted as a Sail bitvector literal (so `pass:[_]`
can be used as a separator) with an explicit integer length. If the
value is shorter than the desired width it will be zero-extended. If
it is larger then any high bits above the stated width will be ignored
(care should be taken to avoid this). In addition to `0b` and `0x`
prefixed literals, a decimal value can also be used (also supporting
`pass:[_]` separators), for example:

[source,json]
----
{ "len" : 32, "value" : "1_000_000" }
----

There are some cases where a specification might need many
configuration options. Consider the case of RISC-V PMP registers,
where there are up to 64 such registers, and each one might be
configured differently. To support this, we allow reading sequences of
JSON values into Sail vectors and lists.

=== Runtime Configuration with Sail to C

The runtime configuration functions are included in the
`sail_config.h` header in the `lib/json` subdirectory of the Sail
distribution. The `sail_config_set_file` function loads a
configuration, and should be called before running any code in a
configurable model. The loaded configuration data can be freed by
using the `sail_config_cleanup` function.

[source,c]
----
void sail_config_set_file(const char *path);

void sail_config_cleanup(void);
----

=== Validating Configurations with JSON Schema
