(lang dune 3.21)
(using rocq 0.11)

(package
 (name rocq_sail)
 (synopsis "Sail core definitions in Rocq")
 (depends
  (rocq-stdlib (>= 9.1.1))
  (rocq-stdpp (>= 1.13.0))
  (rocq-stdpp-bitvector (>= 1.13.0))))
