#!/bin/bash

if [ ! -d bbv ]; then
  echo Run clean from the coq-riscv directory
  exit 1
fi

set -ex
cd bbv
make
cd ../sail/lib/coq
make
cd ../../riscv
coqc -R ../../bbv/theories bbv -R ../lib/coq Sail riscv_extras.v
coqc -R ../../bbv/theories bbv -R ../lib/coq Sail riscv_types.v
coqc -R ../../bbv/theories bbv -R ../lib/coq Sail riscv.v
