(include_subdirs qualified)

(rocq.theory
 (name Sail)
 (modules
  Ast
  AstInduction
  Bit
  BitList
  BvUtil
  Domain.Lattice
  Domain.Interval
  Domain.AbsBitvector
  Domain.AbsValue
  Domain.TransferBitvectorInterval
  IdUtil
  ListUtil
  OptionUtil
  PatternMatch
  SailBase
  Semantics
  Tactics
  TypeAnnot
  ValueType
  ZAst)
 (package rocq_sail)
 (theories Stdlib Ltac2 stdpp stdpp.bitvector))
