(include_subdirs qualified)

(rocq.theory
 (name Sail)
 (modules
  Ast
  AstInduction
  Base
  Bit
  BitList
  Domain.Lattice
  Domain.Interval
  Domain.AbsBitvector
  Domain.AbsValue
  IdUtil
  ListUtil
  OptionUtil
  PatternMatch
  Semantics
  Tactics
  TypeAnnot
  ValueSemilattice
  ValueType
  ZAst)
 (package rocq_sail)
 (theories Stdlib Ltac2 stdpp))
