\providecommand\saildoclabelled[2]{\phantomsection\label{#1}#2}

\newcommand{\sailtypeast}{\saildoclabelled{typezast}{\saildoctype{}{\lstinputlisting[language=sail]{out/typezast6bb070d12e82e4887160cdfd016230c8.tex}}}}

\newcommand{\sailvalexecute}{\saildoclabelled{zexecute}{\saildocval{}{\lstinputlisting[language=sail]{out/valzexecute33a689e3a631b9b905b85461d3814943.tex}}}}

\newcommand{\sailfclCAndPermexecute}{\saildoclabelled{fclCAndPermzexecute}{\saildocfcl{Capability register \emph{cd} is replaced with the contents of capability
register \emph{cs1} with the \cperms{} field set to the bitwise-AND of
its previous value and bits 0 .. 10 of integer register \emph{rs2}
and the \cuperms{} field set to the bitwise and of its previous value
and bits \hyperref[table:pseudocode-constants]{\emph{first\_uperm}} ..
\hyperref[table:pseudocode-constants]{\emph{last\_uperm}} of \emph{rd}.

}{\lstinputlisting[language=sail]{out/fclCAndPermzexecute33a689e3a631b9b905b85461d3814943.tex}}}}

\newcommand{\sailfclCSetFlagsexecute}{\saildoclabelled{fclCSetFlagszexecute}{\saildocfcl{}{\lstinputlisting[language=sail]{out/fclCSetFlagszexecute33a689e3a631b9b905b85461d3814943.tex}}}}



\newcommand{\sailval}[1]{
  \ifstrequal{#1}{execute}{\sailvalexecute}{}}

\newcommand{\sailrefval}[2]{
  \ifstrequal{#1}{execute}{\hyperref[zexecute]{#2}}{}}

\newcommand{\sailfn}[1]{
  }

\newcommand{\sailreffn}[2]{
  }

\newcommand{\sailtype}[1]{
  \ifstrequal{#1}{ast}{\sailtypeast}{}}

\newcommand{\sailreftype}[2]{
  \ifstrequal{#1}{ast}{\hyperref[typezast]{#2}}{}}
