(executable
 (name sail_plugin_doc)
 (modes
  (native plugin)
  (byte plugin))
 (link_flags -linkall)
 (libraries libsail cmarkit yojson base64)
 (embed_in_plugin_libraries cmarkit base64))

(install
 (section
  (site
   (libsail plugins)))
 (package sail_doc_backend)
 (files sail_plugin_doc.cmxs sail_plugin_doc.cma))
