name: Build RISCV For Lean

on: [push, workflow_dispatch]

env:
  OPAMVERBOSE: 1

jobs:
  build:
    strategy:
      matrix:
        version: [5.2.1]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: System dependencies (ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt install build-essential libgmp-dev z3 cvc4 opam

    - name: Restore cached opam
      id: cache-opam-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.opam
        key: ${{ matrix.os }}-${{ matrix.version }}

    - name: Setup opam
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      run: |
        opam init --yes --no-setup --shell=sh --compiler=${{ matrix.version }}

    - name: Save cached opam
      if: steps.cache-opam-restore.outputs.cache-hit != 'true'
      id: cache-opam-save
      uses: actions/cache/save@v4
      with:
        path: ~/.opam
        key: ${{ steps.cache-opam-restore.outputs.cache-primary-key }}

    - name: Install Sail
      run: |
        eval $(opam env)
        opam pin --yes --no-action add .
        opam install sail --yes

    - name: Build the `Sail RISCV Model with Lean`
      run: |
        git clone https://github.com/RaitoBezarius/sail-riscv.git
        cd sail-riscv
        git checkout lean
        eval $(opam config env)
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        # This patch is needed to work around https://github.com/rems-project/sail/issues/1003.
        patch -p1 < ../../sail/.github/workflows/build-riscv-lean-workaround-riscv.patch
        cmake --build build/ --target generated_lean_rv64d_lean
