name: Lower bounds

on: [workflow_dispatch]

jobs:
  lower-bounds:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ocaml-compiler: [5.0.0]

    runs-on: ${{ matrix.os }}

    env:
      OPAMCONFIRMLEVEL: unsafe-yes
      OPAMYES: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: opam install . --deps-only

      - name: Install opam-0install
        run: opam install opam-0install

      - name: Downgrade dependencies
        # Option 1: allow OCaml version downgrade
        run: opam install --unlock-base $(opam exec -- opam-0install --prefer-oldest sail)
        # Option 2: forbid OCaml version downgrade (specify ocaml-base-compiler again to prevent it from being downgraded)
        # run: opam install $(opam exec -- opam-0install --prefer-oldest sail ocaml-base-compiler.${{ matrix.ocaml-compiler }})

      - name: Build
        run: opam exec -- dune build --release
